name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: npm install

      - name: Pull latest commit
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/simple-express-wowrack-cloudraya
            git pull origin master
